server:
  port: 8080

#  eureka.client.register-with-eureka=true
#  eureka.client.fetch-registry=true
#  eureka.client.serviceUrl.defaultZone=http://localhost:8763/eureka/
#  instance.hostname=localhost

eureka:
#  instance:
#    preferIpAddress: true
  client:
#    instance:
#      preferIpAddress: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
#  instance:
#    hostname: ${vcap.application.uris[0]:localhost}
#    preferIpAddress: true

#management:
#  endpoint:
#    gateway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: gateway
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER-SERVICE
#          uri: http://localhost:8081/
          predicates:
            - Path=/user-service/api/**
          filters:
            - AuthFilter
        - id: doctor
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor-service/api/**
          filters:
            - AuthFilter
        - id: auth
          uri: lb://AUTH-SERVICE
          # uri: http://localhost:8090/
          predicates:
            - Path=/auths/api/**
#server:
#  port: 8080
#
#management:
#  endpoint.gateway.enabled: true
#  endpoints.web.exposure.include: gateway
#
#spring:
#  application.name: backend-user
#  cloud:
#    gateway:
#      discovery.locator.enabled: true
#      routes:
#        - id: service-books-id
#          uri: lb://service-books
#          predicates:
#            Path=/books/**
#          filters:
#            - name: AuthFilter
#        - id: service-prices-id
#          uri: lb://service-prices
#          predicates:
#            Path=/prices/**
##          filters:
##            - AuthFilter
#        - id: service-users-sign-in
#          uri: lb://service-users
#          predicates:
#            Path=/users/signIn
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8763/eureka