server:
  port: 8090
  servlet:
    context-path: /auths

spring:
  application:
    name: auth-service

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8763/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka